# Form implementation generated from reading ui file 'ychenik.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ychenik(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.btn_spravka = QtWidgets.QPushButton(parent=self.frame)
        self.btn_spravka.setGeometry(QtCore.QRect(644, 0, 71, 23))
        self.btn_spravka.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_spravka.setObjectName("btn_spravka")
        self.btn_exit = QtWidgets.QPushButton(parent=self.frame)
        self.btn_exit.setGeometry(QtCore.QRect(720, 0, 75, 23))
        self.btn_exit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_exit.setObjectName("btn_exit")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(60, 110, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tableView = QtWidgets.QTableView(parent=self.frame)
        self.tableView.setGeometry(QtCore.QRect(60, 150, 671, 381))
        self.tableView.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableView.setObjectName("tableView")
        self.btn_excel = QtWidgets.QPushButton(parent=self.frame)
        self.btn_excel.setGeometry(QtCore.QRect(60, 550, 81, 23))
        self.btn_excel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_excel.setObjectName("btn_excel")
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_spravka.setText(_translate("MainWindow", "Справка"))
        self.btn_exit.setText(_translate("MainWindow", "Выход"))
        self.label.setText(_translate("MainWindow", "Отметки:"))
        self.btn_excel.setText(_translate("MainWindow", "Вывод в Excel"))
